// gaming-history.js — события игровой индустрии по дням года
(function() {
  'use strict';

  var CONTAINER = 'today-in-history';
  if (!document.getElementById(CONTAINER)) return;

  var today = new Date();
  var mm = String(today.getMonth() + 1).padStart(2, '0');
  var dd = String(today.getDate()).padStart(2, '0');
  var key = mm + '-' + dd;

  var events = {
    '01-01': {y:1998,t:'Starcraft',d:'Blizzard выпускает Starcraft в Южной Корее — игра становится национальным киберспортом'},
    '01-02': {y:2007,t:'Steam сообщество',d:'Valve запускает Steam Community — профили, друзья и группы'},
    '01-03': {y:2006,t:'Xbox 360 дефицит',d:'Microsoft признаёт глобальный дефицит Xbox 360 после рекордных продаж'},
    '01-04': {y:2011,t:'OnLive',d:'Запущен облачный сервис OnLive — игры без консоли и ПК, за 5 лет до Stadia'},
    '01-05': {y:2017,t:'Scalebound отменён',d:'Microsoft отменяет Scalebound от PlatinumGames после 4 лет разработки'},
    '01-06': {y:2021,t:'CD Projekt RED',d:'CD Projekt RED приносит извинения за Cyberpunk 2077 на консолях — начало refund-программы'},
    '01-07': {y:2019,t:'AMD Radeon VII',d:'AMD анонсирует Radeon VII — первую 7-нм игровую видеокарту на CES 2019'},
    '01-08': {y:2020,t:'GeForce NOW',d:'NVIDIA запускает GeForce NOW для всех — облачный гейминг с RTX'},
    '01-09': {y:2007,t:'iPhone и игры',d:'Стив Джобс представляет iPhone — рождение мобильного гейминга'},
    '01-10': {y:2013,t:'Steam Box',d:'Valve и Xi3 анонсируют Piston — первый прототип Steam Machine на CES 2013'},
    '01-11': {y:2005,t:'Resident Evil 4',d:'Capcom выпускает Resident Evil 4 на GameCube — революция жанра survival horror'},
    '01-12': {y:2015,t:'Windows 10',d:'Microsoft анонсирует Windows 10 с DirectX 12 и Xbox-интеграцией'},
    '01-13': {y:2022,t:'Take-Two + Zynga',d:'Take-Two покупает Zynga за $12.7 млрд — крупнейшая сделка в истории игр'},
    '01-14': {y:2014,t:'SteamOS',d:'Valve выпускает бета-версию SteamOS для Steam Machines'},
    '01-15': {y:2019,t:'Bungie + Activision',d:'Bungie разрывает партнёрство с Activision и забирает права на Destiny'},
    '01-16': {y:2018,t:'PUBG рекорд',d:'PUBG достигает 3.2 млн одновременных игроков в Steam — абсолютный рекорд'},
    '01-17': {y:2017,t:'Scalebound отмена',d:'Microsoft официально подтверждает отмену Scalebound'},
    '01-18': {y:2022,t:'Microsoft + Activision',d:'Microsoft объявляет о покупке Activision Blizzard за $68.7 млрд — шок индустрии'},
    '01-19': {y:2012,t:'Minecraft 20M',d:'Minecraft продаётся тиражом 20 миллионов копий — игра-феномен'},
    '01-20': {y:2020,t:'Tencent + Riot',d:'Riot Games становится 100% дочерней компанией Tencent'},
    '01-21': {y:2019,t:'Resident Evil 2',d:'Capcom выпускает ремейк Resident Evil 2 — эталон ремейков на RE Engine'},
    '01-22': {y:2013,t:'The Last of Us',d:'Naughty Dog объявляет дату выхода The Last of Us — 14 июня 2013'},
    '01-23': {y:1991,t:'id Software',d:'Джон Кармак и Джон Ромеро основывают id Software — рождение FPS-жанра'},
    '01-24': {y:2014,t:'Steam VR',d:'Valve впервые демонстрирует прототип Steam VR-шлема на Steam Dev Days'},
    '01-25': {y:2010,t:'Mass Effect 2',d:'BioWare выпускает Mass Effect 2 — одна из лучших RPG в истории игр'},
    '01-26': {y:2018,t:'Fortnite рекорд',d:'Fortnite достигает 45 млн игроков — феномен Battle Royale'},
    '01-27': {y:1998,t:'Half-Life',d:'Sierra и Valve анонсируют Half-Life на модифицированном движке Quake'},
    '01-28': {y:2021,t:'GameStop феномен',d:'Акции GameStop взлетают на 1500% благодаря Reddit-трейдерам r/wallstreetbets'},
    '01-29': {y:2019,t:'Metro Exodus',d:'4A Games выпускает Metro Exodus — технологический шедевр на 4A Engine'},
    '01-30': {y:2007,t:'Vista + игры',d:'Microsoft выпускает Windows Vista с DirectX 10 — массовые проблемы с драйверами'},
    '01-31': {y:1997,t:'Final Fantasy VII',d:'Square выпускает Final Fantasy VII в Японии — рождение JRPG на PlayStation'},

    '02-01': {y:1991,t:'Commander Keen',d:'id Software выпускает последнюю часть Commander Keen — до Wolfenstein 3D'},
    '02-02': {y:2016,t:'XCOM 2',d:'Firaxis выпускает XCOM 2 — эволюция тактических стратегий'},
    '02-03': {y:1995,t:'День Pixar',d:'Pixar выпускает RenderMan — технологию рендера для игровых синематиков'},
    '02-04': {y:2019,t:'Apex Legends',d:'Respawn внезапно выпускает Apex Legends — 25 млн игроков за неделю без маркетинга'},
    '02-05': {y:2013,t:'Tomb Raider',d:'Crystal Dynamics перезапускает Tomb Raider — новый облик Лары Крофт'},
    '02-06': {y:1999,t:'Sid Meier',d:'Firaxis Games основана Сидом Мейером — культовые стратегии Civilization'},
    '02-07': {y:2017,t:'For Honor',d:'Ubisoft выпускает For Honor — инновационная боевая система Art of Battle'},
    '02-08': {y:2018,t:'Nintendo Labo',d:'Nintendo анонсирует Labo — картонные аксессуары для Switch'},
    '02-09': {y:2005,t:'EA + ESPN',d:'EA Sports заключает эксклюзивный 15-летний контракт с ESPN'},
    '02-10': {y:2015,t:'Evolve',d:'Turtle Rock выпускает Evolve — амбициозный асимметричный шутер 4v1'},
    '02-11': {y:2022,t:'Lost Ark',d:'Lost Ark выходит на Западе — 1.3 млн одновременных игроков в Steam за сутки'},
    '02-12': {y:2014,t:'Flappy Bird',d:'Разработчик удаляет Flappy Bird из магазинов — игра приносила $50 000 в день'},
    '02-13': {y:2007,t:'Crysis физика',d:'Crytek демонстрирует физику CryEngine 2 на GDC 2007 — будущее игр'},
    '02-14': {y:2005,t:'YouTube',d:'Зарегистрирован домен YouTube.com — будущая платформа гейминг-контента'},
    '02-15': {y:2011,t:'MvC3',d:'Capcom выпускает Marvel vs Capcom 3 — эпичные кроссоверы файтингов'},
    '02-16': {y:2023,t:'Hogwarts Legacy',d:'Hogwarts Legacy бьёт рекорды — 12 млн копий за 2 недели'},
    '02-17': {y:2017,t:'Nioh',d:'Team Ninja выпускает Nioh — самурайский souls-like, рождённый из отменённого проекта'},
    '02-18': {y:2020,t:'Amazon Games',d:'Amazon запускает New World в альфа-тест — игра-долгострой на Lumberyard'},
    '02-19': {y:2016,t:'Firewatch',d:'Campo Santo выпускает Firewatch — шедевр нарративного дизайна'},
    '02-20': {y:2002,t:'Steam анонс',d:'Gabe Newell анонсирует Steam на GDC 2002 — «сервис будет бесплатным»'},
    '02-21': {y:1986,t:'Legend of Zelda',d:'Nintendo выпускает The Legend of Zelda в Японии — рождение жанра action-adventure'},
    '02-22': {y:2019,t:'Anthem',d:'BioWare выпускает Anthem — крупнейший провал студии, потеря $100M+'},
    '02-23': {y:1999,t:'Gran Turismo 2',d:'Polyphony выпускает Gran Turismo 2 — 650 машин, рекорд PlayStation'},
    '02-24': {y:2022,t:'Elden Ring',d:'FromSoftware выпускает Elden Ring — 12 млн копий за 18 дней, феномен года'},
    '02-25': {y:2015,t:'UE4 бесплатно',d:'Epic Games делает Unreal Engine 4 бесплатным — революция инди-разработки'},
    '02-26': {y:2013,t:'PS4 анонс',d:'Sony анонсирует PlayStation 4 на специальном ивенте в Нью-Йорке'},
    '02-27': {y:1996,t:'Pokemon',d:'Nintendo выпускает Pokemon Red и Green в Японии — старт глобального феномена'},
    '02-28': {y:2006,t:'TES IV Oblivion',d:'Bethesda объявляет дату выхода The Elder Scrolls IV: Oblivion — 20 марта'},
    '02-29': {y:2012,t:'SSX',d:'EA возрождает серию SSX — культовый сноуборд-экшен возвращается на PS3/Xbox360'},

    '03-01': {y:1994,t:'Sony PlayStation',d:'Sony анонсирует PlayStation в Японии — конец эпохи Nintendo-картриджей'},
    '03-02': {y:2017,t:'Nintendo Switch',d:'Nintendo выпускает Switch с Breath of the Wild — 1.5M за неделю, триумф'},
    '03-03': {y:2017,t:'Zelda BOTW',d:'The Legend of Zelda: Breath of the Wild — 10/10 от 52 изданий, революция open-world'},
    '03-04': {y:2014,t:'South Park SoT',d:'Obsidian выпускает South Park: The Stick of Truth — RPG-шедевр по лицензии'},
    '03-05': {y:2020,t:'PlayStation 2',d:'PS2 отмечает 20 лет — 158M проданных консолей, рекорд навсегда'},
    '03-06': {y:2018,t:'FFXV Windows',d:'Final Fantasy XV выходит на ПК с поддержкой NVIDIA GameWorks и модами'},
    '03-07': {y:2003,t:'Metroid Prime',d:'Retro Studios выпускает Metroid Prime — идеальный переход в 3D от первого лица'},
    '03-08': {y:2019,t:'Devil May Cry 5',d:'Capcom выпускает Devil May Cry 5 — 11 лет ожидания и триумф жанра'},
    '03-09': {y:2020,t:'GeForce NOW',d:'NVIDIA запускает GeForce NOW из беты — 30M+ пользователей облачного гейминга'},
    '03-10': {y:2015,t:'Cities Skylines',d:'Colossal Order выпускает Cities: Skylines — убийца SimCity, 12M+ копий'},
    '03-11': {y:2021,t:'Xbox Bethesda',d:'Microsoft завершает покупку ZeniMax Media за $7.5 млрд — Bethesda теперь Xbox'},
    '03-12': {y:2004,t:'CS: Source',d:'Valve выпускает Counter-Strike: Source на движке Source Engine'},
    '03-13': {y:2008,t:'Brawl',d:'Nintendo выпускает Super Smash Bros. Brawl — 13M+ продаж на Wii'},
    '03-14': {y:2024,t:'Pi Day',d:'Игровая индустрия отмечает Pi Day — скидки на математические игры'},
    '03-15': {y:2016,t:'Need for Speed',d:'EA выпускает перезапуск Need for Speed — всегда онлайн, всегда спорно'},
    '03-16': {y:2018,t:'Sea of Thieves',d:'Rare выпускает Sea of Thieves — пиратская MMO-песочница с water-физикой'},
    '03-17': {y:2015,t:'Battlefield Hardline',d:'Visceral Games выпускает Battlefield Hardline — полиция против бандитов'},
    '03-18': {y:2005,t:'God of War',d:'Santa Monica Studio выпускает God of War на PS2 — Кратос становится иконой'},
    '03-19': {y:2020,t:'DOOM Eternal',d:'id Software выпускает DOOM Eternal — адреналиновый шутер года, 90+ Metacritic'},
    '03-20': {y:2020,t:'Animal Crossing NH',d:'Nintendo выпускает Animal Crossing: New Horizons — 40M+ копий, спасение в пандемию'},
    '03-21': {y:2017,t:'Mass Effect Andromeda',d:'BioWare выпускает Mass Effect: Andromeda — скандал с анимациями лиц'},
    '03-22': {y:2019,t:'Sekiro',d:'FromSoftware выпускает Sekiro: Shadows Die Twice — GOTY 2019, битва с мечом'},
    '03-23': {y:2021,t:'GDC 2021',d:'GDC 2021 полностью онлайн — анонсы Unreal Engine 5 и новых инструментов'},
    '03-24': {y:2020,t:'Half-Life Alyx',d:'Valve выпускает Half-Life: Alyx — первая AAA-игра для VR, 92 Metacritic'},
    '03-25': {y:2014,t:'Facebook + Oculus',d:'Facebook покупает Oculus VR за $2 млрд — большие деньги в виртуальной реальности'},
    '03-26': {y:2013,t:'BioShock Infinite',d:'Irrational Games выпускает BioShock Infinite — сюжетный шедевр с концовкой-шоком'},
    '03-27': {y:1998,t:'Baldur\'s Gate',d:'BioWare выпускает Baldur\'s Gate — золотой стандарт RPG от Wizards of the Coast'},
    '03-28': {y:2000,t:'Diablo II',d:'Blizzard анонсирует Diablo II — 17 лет поддержки, миллионы игроков'},
    '03-29': {y:2019,t:'Path of Exile',d:'Grinding Gear Games анонсирует Path of Exile 2 на ExileCon — конец Diablo?'},
    '03-30': {y:2004,t:'Far Cry',d:'Crytek выпускает Far Cry — техническая революция с открытыми островами'},
    '03-31': {y:1998,t:'StarCraft глоб.',d:'Blizzard выпускает StarCraft глобально — эпоха киберспорта начинается'},

    '04-01': {y:2005,t:'April Fools',d:'Blizzard анонсирует Pandaren Express — доставка еды в WoW, лучший первоапрельский пранк'},
    '04-02': {y:2019,t:'Borderlands 3',d:'Gearbox анонсирует Borderlands 3 — возвращение миллиардов пушек'},
    '04-03': {y:1995,t:'Saturn USA',d:'Sega выпускает Saturn в США на 4 месяца раньше — E3-сюрприз за $399'},
    '04-04': {y:1975,t:'Microsoft',d:'Билл Гейтс и Пол Аллен основывают Microsoft — будущий Xbox и DirectX'},
    '04-05': {y:2016,t:'Quantum Break',d:'Remedy выпускает Quantum Break — гибрид игры и сериала от создателей Max Payne'},
    '04-06': {y:1992,t:'Wolfenstein 3D',d:'id Software выпускает Wolfenstein 3D — первый шутер от первого лица'},
    '04-07': {y:2015,t:'GTA V PC',d:'Rockstar выпускает GTA V на ПК спустя 18 месяцев — 60 fps, моды, редактор'},
    '04-08': {y:2020,t:'RE3 Remake',d:'Capcom выпускает Resident Evil 3 Remake — Немезис преследует Джилл'},
    '04-09': {y:2013,t:'Defiance',d:'Trion Worlds выпускает Defiance — MMO-шутер, синхронизированный с ТВ-сериалом'},
    '04-10': {y:2014,t:'Kinect умер',d:'Microsoft прекращает производство Kinect — конец жестового гейминга'},
    '04-11': {y:1994,t:'ESRB создан',d:'Сенат США требует рейтингов — рождение ESRB после слушаний по Mortal Kombat'},
    '04-12': {y:2011,t:'Portal 2',d:'Valve выпускает Portal 2 — кооперативный шедевр с Wheatley и GLaDOS'},
    '04-13': {y:2010,t:'Splash Damage',d:'Splash Damage анонсирует Brink — паркур-шутер с кастомизацией'},
    '04-14': {y:2015,t:'GTA V PC',d:'GTA V на ПК получает 96 на Metacritic — лучшая версия игры'},
    '04-15': {y:1994,t:'ESRB',d:'ESRB начинает работу — первые рейтинги для игровой индустрии США'},
    '04-16': {y:2013,t:'Injustice',d:'NetherRealm выпускает Injustice: Gods Among Us — DC-файтинг от создателей MK'},
    '04-17': {y:2018,t:'God of War',d:'Santa Monica Studio выпускает God of War на PS4 — GOTY 2018, переизобретение серии'},
    '04-18': {y:2019,t:'Cuphead Switch',d:'Cuphead выходит на Nintendo Switch — Microsoft разрешает эксклюзив на консоли конкурента'},
    '04-19': {y:2010,t:'Steam Mac',d:'Valve запускает Steam на Mac — Portal и Team Fortress 2 для яблочных геймеров'},
    '04-20': {y:2018,t:'Nintendo Labo',d:'Nintendo выпускает Labo — картонные контроллеры-конструкторы для Switch'},
    '04-21': {y:1989,t:'Game Boy',d:'Nintendo выпускает Game Boy в Японии — Tetris в комплекте, 118M проданных'},
    '04-22': {y:2014,t:'NES Remix',d:'Nintendo выпускает NES Remix — ретро-челленджи с классическими играми'},
    '04-23': {y:2019,t:'Mortal Kombat 11',d:'NetherRealm выпускает MK11 — лучшая графика в файтингах с фаталити'},
    '04-24': {y:2007,t:'Guitar Hero II',d:'Harmonix выпускает Guitar Hero II на Xbox 360 — пик музыкальных игр'},
    '04-25': {y:2019,t:'Ubisoft анонс',d:'Ubisoft анонсирует подписочный сервис Uplay+ с доступом к 100+ играм'},
    '04-26': {y:2019,t:'Days Gone',d:'Sony Bend выпускает Days Gone — зомби-выживание с ордами фриков'},
    '04-27': {y:2010,t:'Super Mario 25',d:'Nintendo отмечает 25-летие Super Mario Bros. — Silver Mario в комплекте'},
    '04-28': {y:2015,t:'Steam Workshop',d:'Valve разрешает продавать моды в Steam — скандал с платными модами Skyrim'},
    '04-29': {y:2020,t:'Gears Tactics',d:'The Coalition выпускает Gears Tactics — XCOM-style в мире Gears of War'},
    '04-30': {y:2013,t:'Dead Island Riptide',d:'Deep Silver выпускает Dead Island Riptide — зомби-экшен на тропическом острове'},

    '05-01': {y:2016,t:'Nintendo NX',d:'Nintendo впервые подтверждает кодовое имя NX — будущая Switch'},
    '05-02': {y:2017,t:'Prey',d:'Arkane Studios выпускает Prey — иммерсивный сим на космической станции Талос-I'},
    '05-03': {y:2012,t:'Bungie + Activision',d:'Bungie и Activision подписывают 10-летний контракт на Destiny — $500M бюджет'},
    '05-04': {y:1972,t:'Magnavox Odyssey',d:'Magnavox демонстрирует Odyssey — самую первую домашнюю игровую консоль'},
    '05-05': {y:2015,t:'Wolfenstein TOB',d:'MachineGames выпускает Wolfenstein: The Old Blood — приквел New Order'},
    '05-06': {y:2020,t:'Xbox Series X',d:'Microsoft проводит Inside Xbox — первые геймплейные кадры Series X'},
    '05-07': {y:2015,t:'Remedy Quantum',d:'Remedy Entertainment становится публичной компанией на бирже Хельсинки'},
    '05-08': {y:2018,t:'Conan Exiles',d:'Funcom выпускает Conan Exiles из раннего доступа — выживание с системой рабов'},
    '05-09': {y:1980,t:'Pac-Man',d:'Namco выпускает Pac-Man в Японии — аркадный автомат, изменивший всё'},
    '05-10': {y:2016,t:'Uncharted 4',d:'Naughty Dog выпускает Uncharted 4: A Thief\'s End — финал приключений Дрейка'},
    '05-11': {y:2009,t:'Minecraft',d:'Маркус Перссон выпускает первую публичную версию Minecraft — игра-феномен'},
    '05-12': {y:2016,t:'DOOM 2016',d:'id Software перезапускает DOOM — идеальный reboot с металлом и демонами'},
    '05-13': {y:2003,t:'E3 2003',d:'E3 2003 — Valve показывает Half-Life 2 с физикой Source — зал встаёт'},
    '05-14': {y:2019,t:'Rage 2',d:'Avalanche и id выпускают Rage 2 — Mad Max встречает DOOM в открытом мире'},
    '05-15': {y:2012,t:'Diablo III',d:'Blizzard выпускает Diablo III — 3.5M копий за 24 часа, серверы падают'},
    '05-16': {y:2011,t:'LA Noire',d:'Team Bondi выпускает LA Noire — революция лицевой анимации MotionScan'},
    '05-17': {y:1996,t:'Valve основана',d:'Гейб Ньюэлл и Майк Харрингтон основывают Valve — бывшие сотрудники Microsoft'},
    '05-18': {y:2010,t:'Red Dead Redemption',d:'Rockstar выпускает Red Dead Redemption — шедевр вестерна и открытого мира'},
    '05-19': {y:2015,t:'The Witcher 3',d:'CD Projekt RED выпускает The Witcher 3: Wild Hunt — 800+ наград GOTY, эталон RPG'},
    '05-20': {y:2014,t:'Wolfenstein TNO',d:'MachineGames выпускает Wolfenstein: The New Order — возрождение классики'},
    '05-21': {y:2019,t:'Team Sonic Racing',d:'Sumo Digital выпускает Team Sonic Racing — кооперативные гонки с Ежом'},
    '05-22': {y:1996,t:'Quake',d:'id Software выпускает Quake — первый полностью 3D-шутер с интернет-мультиплеером'},
    '05-23': {y:2017,t:'Far Cry 5 анонс',d:'Ubisoft анонсирует Far Cry 5 — культ в Монтане, политический скандал'},
    '05-24': {y:2018,t:'Dark Souls Remaster',d:'FromSoftware выпускает Dark Souls Remastered для нового поколения'},
    '05-25': {y:2004,t:'Thief DS',d:'Ion Storm выпускает Thief: Deadly Shadows — стелс-иммерсивный сим'},
    '05-26': {y:2017,t:'Friday the 13th',d:'IllFonic выпускает Friday the 13th: The Game — асимметричный хоррор-мультиплеер'},
    '05-27': {y:2010,t:'Red Dead Redemption',d:'Rockstar празднует 5M проданных копий RDR за первые 2 недели'},
    '05-28': {y:2002,t:'E3 2002',d:'Nintendo показывает The Legend of Zelda: The Wind Waker — фанаты в ярости от cel-shading'},
    '05-29': {y:2018,t:'Sega Mega Drive',d:'Sega анонсирует Sega Mega Drive Mini — ретро-консоль с 40 играми'},
    '05-30': {y:2019,t:'Death Stranding',d:'Хидео Кодзима показывает геймплей Death Stranding — мир в шоке от замысла'},
    '05-31': {y:1992,t:'Wolfenstein 3D',d:'id Software выпускает Wolfenstein 3D как shareware — вирусное распространение'},

    '06-01': {y:2010,t:'E3 2010',d:'Nintendo показывает 3DS на E3 — 3D без очков, революция портативок'},
    '06-02': {y:2015,t:'Fallout 4',d:'Bethesda анонсирует Fallout 4 трейлером-бомбой — 12M просмотров за сутки'},
    '06-03': {y:2009,t:'E3 2009',d:'Microsoft показывает Project Natal на E3 — будущий Kinect с Milo'},
    '06-04': {y:2018,t:'Vampyr',d:'Dontnod выпускает Vampyr — вампирская RPG о моральном выборе в Лондоне 1918'},
    '06-05': {y:2020,t:'The Last of Us 2',d:'История TLOU2 утекает в сеть — крупнейший спойлер-скандал в истории игр'},
    '06-06': {y:1984,t:'Tetris',d:'Алексей Пажитнов создаёт Тетрис в ВЦ АН СССР — самая продаваемая игра в истории'},
    '06-07': {y:2019,t:'E3 2019',d:'EA Play 2019 — Jedi Fallen Order, Apex Legends Season 2, Battlefield V'},
    '06-08': {y:2023,t:'Summer Game Fest',d:'Summer Game Fest 2023 — анонсы Alan Wake 2, Spider-Man 2, Final Fantasy VII Rebirth'},
    '06-09': {y:2019,t:'Xbox E3 2019',d:'Microsoft показывает Project Scarlett на E3 — Xbox Series X, Halo Infinite'},
    '06-10': {y:2018,t:'Bethesda E3 2018',d:'Bethesda анонсирует Starfield и The Elder Scrolls VI одним тизером — 5 лет ожидания'},
    '06-11': {y:2013,t:'E3 2013',d:'Sony убивает used games — «This is how you share games on PS4» — удар по Xbox One'},
    '06-12': {y:2017,t:'E3 2017',d:'Ubisoft анонсирует Beyond Good & Evil 2 на E3 — 15 лет после оригинала'},
    '06-13': {y:2022,t:'Xbox Showcase',d:'Xbox & Bethesda Showcase 2022 — Starfield геймплей, Diablo IV, Redfall'},
    '06-14': {y:2013,t:'The Last of Us',d:'Naughty Dog выпускает The Last of Us на PS3 — 95 Metacritic, шедевр навсегда'},
    '06-15': {y:2015,t:'E3 2015',d:'Sony анонсирует The Last Guardian, Shenmue III и FF7 Remake — три мечты за ночь'},
    '06-16': {y:2021,t:'FFVII Remake',d:'Final Fantasy VII Remake Intergrade выходит на PS5 с DLC про Юффи'},
    '06-17': {y:1980,t:'Atari VCS',d:'Atari устраивает похороны 700 000 картриджей E.T. в пустыне Нью-Мексико'},
    '06-18': {y:2020,t:'The Last of Us 2',d:'Naughty Dog выпускает The Last of Us Part II — самая противоречивая игра десятилетия'},
    '06-19': {y:2020,t:'TLOU2 отзывы',d:'The Last of Us Part II получает рекордные 300+ GOTY наград'},
    '06-20': {y:2019,t:'Harry Potter RPG',d:'Утечка геймплея Harry Potter RPG — фанаты сходят с ума, WB отрицает'},
    '06-21': {y:1996,t:'Nintendo 64',d:'Nintendo выпускает Nintendo 64 в Японии — 3D-революция с аналоговым стиком'},
    '06-22': {y:1990,t:'Commander Keen',d:'id Software выпускает первый эпизод Commander Keen — рождение PC-платформера'},
    '06-23': {y:1991,t:'Sonic the Hedgehog',d:'Sega выпускает Sonic the Hedgehog на Genesis — начало консольных войн'},
    '06-24': {y:1993,t:'Myst',d:'Cyan выпускает Myst — самый продаваемый ПК-тайтл до прихода The Sims'},
    '06-25': {y:2015,t:'Batman Arkham Knight',d:'Rocksteady выпускает Arkham Knight — финал трилогии с Бэтмобилем и провальным ПК-портом'},
    '06-26': {y:2018,t:'Nier Automata',d:'Nier: Automata проходит 3.5M продаж — успех, спасший PlatinumGames'},
    '06-27': {y:1998,t:'Banjo-Kazooie',d:'Rare выпускает Banjo-Kazooie на N64 — платформер-шедевр от создателей DK Country'},
    '06-28': {y:2002,t:'ESPN NFL 2K5',d:'Sega выпускает ESPN NFL 2K5 за $19.99 — ценовая война, убившая конкурента Madden'},
    '06-29': {y:2007,t:'iPhone',d:'Apple выпускает первый iPhone — мобильный гейминг меняется навсегда'},
    '06-30': {y:2000,t:'Homeworld',d:'Relic выпускает Homeworld: Cataclysm — космическая RTS с атмосферой ужаса'},

    '07-01': {y:2015,t:'Сделка дня',d:'Sony закрывает PlayStation Mobile — конец мобильной платформы для Vita'},
    '07-02': {y:2019,t:'Super Mario Maker 2',d:'Nintendo выпускает Super Mario Maker 2 — бесконечные уровни от сообщества'},
    '07-03': {y:1997,t:'GoldenEye 007',d:'Rare анонсирует GoldenEye 007 на E3 1997 — шутер, определивший консольный жанр'},
    '07-04': {y:2012,t:'End of E3',d:'E3 2012 называют «последним великим E3» — Wii U, Watch Dogs, TLOU'},
    '07-05': {y:2017,t:'Crash Bandicoot',d:'Vicarious Visions выпускает Crash Bandicoot N. Sane Trilogy — ремейк-триумф'},
    '07-06': {y:1999,t:'Aliens vs Predator',d:'Rebellion выпускает Aliens vs Predator на ПК — три кампании, культовый хоррор'},
    '07-07': {y:2015,t:'Rocket League',d:'Psyonix выпускает Rocket League — футбол на машинах, феномен инди-игр'},
    '07-08': {y:2021,t:'Steam Deck',d:'Valve анонсирует Steam Deck — портативный ПК за $399 с доступом ко всей библиотеке Steam'},
    '07-09': {y:2021,t:'Nintendo Switch OLED',d:'Nintendo анонсирует Switch OLED — 7-дюймовый экран, улучшенная подставка, LAN-порт'},
    '07-10': {y:2018,t:'PUBG суд',d:'PUBG Corp подаёт в суд на Epic Games — нарушение авторских прав в Fortnite'},
    '07-11': {y:2014,t:'Gamergate',d:'Начинается Gamergate — крупнейший культурный конфликт в истории игровой индустрии'},
    '07-12': {y:2019,t:'Switch Lite',d:'Nintendo анонсирует Switch Lite — портативная версия за $199 без док-станции'},
    '07-13': {y:2017,t:'GTA Online',d:'GTA Online получает дополнение Gunrunning — контрабанда оружия и бункеры'},
    '07-14': {y:2015,t:'God of War 3',d:'God of War III Remastered выходит на PS4 — Кратос в 1080p 60fps'},
    '07-15': {y:1983,t:'Nintendo Famicom',d:'Nintendo выпускает Famicom в Японии — рождение современной консольной эры'},
    '07-16': {y:2019,t:'Nintendo lawsuit',d:'Nintendo выигрывает $12M в суде против пиратских ROM-сайтов'},
    '07-17': {y:2007,t:'BioShock демо',d:'2K Games выпускает демо BioShock на Xbox 360 — рекордные скачивания'},
    '07-18': {y:2013,t:'Microsoft реструкт.',d:'Microsoft объявляет крупнейшую реструктуризацию — Xbox в центре стратегии'},
    '07-19': {y:2018,t:'Tetris Effect',d:'Enhance Games анонсирует Tetris Effect для PS4 и PSVR — музыкальная медитация'},
    '07-20': {y:2018,t:'No Man\'s Sky NEXT',d:'Hello Games выпускает обновление NEXT — мультиплеер и перерождение игры'},
    '07-21': {y:2022,t:'Stray',d:'BlueTwelve Studio выпускает Stray — кото-симулятор, хит года в Steam'},
    '07-22': {y:2020,t:'Xbox Showcase',d:'Xbox Games Showcase — Halo Infinite геймплей, Fable, Avowed, State of Decay 3'},
    '07-23': {y:2012,t:'Kingdom Hearts 3D',d:'Square Enix выпускает Kingdom Hearts 3D на 3DS — мост к KH3'},
    '07-24': {y:1996,t:'Tomb Raider',d:'Eidos Interactive выпускает Tomb Raider на Sega Saturn — рождение Лары Крофт'},
    '07-25': {y:2014,t:'Oculus SDK',d:'Oculus выпускает DK2 — второй девкит с positional tracking'},
    '07-26': {y:2016,t:'Giant Bomb продан',d:'CBS Interactive покупает Giant Bomb — конец независимой игровой журналистики'},
    '07-27': {y:2017,t:'Fortnite STW',d:'Epic Games запускает ранний доступ Fortnite: Save the World'},
    '07-28': {y:2006,t:'Steam EA',d:'Valve запускает ранний доступ в Steam — Darwinia как тестовый проект'},
    '07-29': {y:2015,t:'Windows 10',d:'Microsoft выпускает Windows 10 с DirectX 12 — новый API для геймеров'},
    '07-30': {y:2019,t:'Fire Emblem 3H',d:'Intelligent Systems выпускает Fire Emblem: Three Houses на Switch'},
    '07-31': {y:1999,t:'Dreamcast',d:'Sega объявляет о прекращении поддержки Saturn и переходе на Dreamcast'},

    '08-01': {y:2017,t:'Tacoma',d:'Fullbright выпускает Tacoma — нарративное приключение на заброшенной лунной станции'},
    '08-02': {y:2018,t:'QuakeCon 2018',d:'DOOM Eternal геймплей на QuakeCon — вторжение демонов на Землю'},
    '08-03': {y:2020,t:'Fall Guys',d:'Mediatonic выпускает Fall Guys — 2M игроков за неделю, феномен лета'},
    '08-04': {y:2015,t:'Rare Replay',d:'Microsoft выпускает Rare Replay — 30 игр за $30 к 30-летию студии'},
    '08-05': {y:2014,t:'Sacred 3',d:'Deep Silver выпускает Sacred 3 — разочарование фанатов, конец серии'},
    '08-06': {y:2013,t:'Dragon\'s Crown',d:'Vanillaware выпускает Dragon\'s Crown — 2D beat-\'em-up с рисованной графикой'},
    '08-07': {y:2015,t:'Pillars of Eternity',d:'Obsidian анонсирует Pillars of Eternity II после успеха первой части'},
    '08-08': {y:2019,t:'Age of Empires II',d:'Microsoft выпускает Age of Empires II: Definitive Edition бета'},
    '08-09': {y:2016,t:'No Man\'s Sky',d:'Hello Games выпускает No Man\'s Sky — амбиции vs реальность, урок всей индустрии'},
    '08-10': {y:2021,t:'Back 4 Blood',d:'Turtle Rock выпускает открытую бету Back 4 Blood — духовный наследник L4D'},
    '08-11': {y:2015,t:'Everybody\'s Gone',d:'The Chinese Room анонсирует Everybody\'s Gone to the Rapture на ПК'},
    '08-12': {y:2020,t:'Halo Infinite',d:'Microsoft откладывает Halo Infinite на 2021 — шок после показа геймплея'},
    '08-13': {y:2013,t:'DuckTales',d:'Capcom выпускает DuckTales Remastered — ностальгический платформер'},
    '08-14': {y:2020,t:'Epic vs Apple',d:'Суд Epic Games vs Apple — Fortnite удалён из App Store, война платформ'},
    '08-15': {y:2000,t:'Deus Ex',d:'Ion Storm Austin выпускает Deus Ex — иммерсивный сим, определивший жанр'},
    '08-16': {y:2016,t:'Valve суд',d:'Valve проигрывает $3M суд в Австралии за отсутствие возвратов до 2015'},
    '08-17': {y:2011,t:'From Dust',d:'Ubisoft Montpellier выпускает From Dust — god-game от создателя Another World'},
    '08-18': {y:2015,t:'Final Fantasy XV',d:'Square Enix анонсирует дату выхода FFXV на Gamescom — 30 сентября 2016'},
    '08-19': {y:2014,t:'Sony Gamescom',d:'Sony анонсирует Until Dawn, Tearaway Unfolded и P.T. на Gamescom 2014'},
    '08-20': {y:2019,t:'Gamescom 2019',d:'Google Stadia — цена и дата запуска, Death Stranding геймплей, Cyberpunk 2077'},
    '08-21': {y:2012,t:'CS:GO',d:'Valve выпускает Counter-Strike: Global Offensive — эволюция киберспорта'},
    '08-22': {y:2017,t:'Uncharted TLL',d:'Naughty Dog выпускает Uncharted: The Lost Legacy — Хлоя в главной роли'},
    '08-23': {y:2016,t:'Deus Ex MD',d:'Eidos Montreal выпускает Deus Ex: Mankind Divided — киберпанк с аугментациями'},
    '08-24': {y:2021,t:'Gamescom 2021',d:'Gamescom ONL — Saints Row reboot, Halo Infinite, Horizon Forbidden West'},
    '08-25': {y:2015,t:'Until Dawn',d:'Supermassive Games выпускает Until Dawn — интерактивное кино-хоррор'},
    '08-26': {y:2014,t:'Infamous FL',d:'Sucker Punch выпускает inFamous: First Light — стэндалон-аддон с Фетч'},
    '08-27': {y:2013,t:'Final Fantasy XIV',d:'Square Enix перезапускает FFXIV как A Realm Reborn — триумфальное возвращение'},
    '08-28': {y:2020,t:'Project xCloud',d:'Microsoft запускает xCloud в составе Game Pass Ultimate — Xbox в облаке'},
    '08-29': {y:1997,t:'GoldenEye 007',d:'Rare выпускает GoldenEye 007 на N64 — 8M копий, культовый splitscreen'},
    '08-30': {y:2013,t:'PS4 дата',d:'Sony объявляет дату выхода PlayStation 4 — 15 ноября 2013 в США'},
    '08-31': {y:2010,t:'Valve экономика',d:'Valve представляет Steam Wallet — виртуальный кошелёк для игр'},

    '09-01': {y:2015,t:'Metal Gear Solid V',d:'Kojima Productions выпускает MGS V: The Phantom Pain — прощание с Кодзимой и Konami'},
    '09-02': {y:1997,t:'Total Annihilation',d:'Cavedog выпускает Total Annihilation — RTS-революция с 3D-юнитами и физикой'},
    '09-03': {y:1995,t:'PlayStation USA',d:'Sony выпускает PlayStation в США за $299 — «299» — самый известный прайс E3'},
    '09-04': {y:2018,t:'Dragon Quest XI',d:'Square Enix выпускает Dragon Quest XI на Западе — классическая JRPG в 4K'},
    '09-05': {y:2012,t:'Steam Greenlight',d:'Valve запускает Steam Greenlight — сообщество голосует за инди-игры'},
    '09-06': {y:2016,t:'PS4 Pro',d:'Sony анонсирует PlayStation 4 Pro — 4K-гейминг на консолях'},
    '09-07': {y:2016,t:'Project Scorpio',d:'Microsoft обещает 6 TFLOPS в Project Scorpio — самая мощная консоль'},
    '09-08': {y:2018,t:'Spider-Man PS4',d:'Insomniac выпускает Spider-Man на PS4 — лучшая супергеройская игра'},
    '09-09': {y:1999,t:'Dreamcast',d:'Sega выпускает Dreamcast в США — 9/9/99, самый успешный запуск в истории'},
    '09-10': {y:2020,t:'Xbox Series S',d:'Утечка Xbox Series S за $299 — Microsoft подтверждает дизайн и цену'},
    '09-11': {y:2014,t:'Destiny',d:'Bungie выпускает Destiny — $500M бюджет, старт 10-летней франшизы'},
    '09-12': {y:2019,t:'Borderlands 3',d:'Gearbox выпускает Borderlands 3 — эксклюзив Epic Games Store, скандал с бомбингом'},
    '09-13': {y:1985,t:'Super Mario Bros.',d:'Nintendo выпускает Super Mario Bros. на NES — 40M копий, спасение индустрии'},
    '09-14': {y:2010,t:'Halo Reach',d:'Bungie выпускает Halo: Reach — прощание студии с серией перед Destiny'},
    '09-15': {y:2015,t:'Destiny TTK',d:'Bungie выпускает Destiny: The Taken King — спасение игры после провального старта'},
    '09-16': {y:2021,t:'Deathloop',d:'Arkane Lyon выпускает Deathloop — иммерсивный сим с временной петлёй, 10/10'},
    '09-17': {y:2013,t:'GTA V',d:'Rockstar выпускает GTA V на PS3 и Xbox 360 — $1 млрд за 3 дня, рекорд индустрии'},
    '09-18': {y:2018,t:'PlayStation Classic',d:'Sony анонсирует PlayStation Classic — 20 ретро-игр в мини-консоли за $99'},
    '09-19': {y:2019,t:'Nintendo Direct',d:'Nintendo Direct — Overwatch на Switch, Tetris 99 DLC, Xenoblade Chronicles'},
    '09-20': {y:2013,t:'SteamOS',d:'Valve анонсирует SteamOS — Linux-дистрибутив для гостиной'},
    '09-21': {y:2020,t:'Microsoft + Bethesda',d:'Microsoft покупает ZeniMax Media за $7.5 млрд — конец эксклюзивов Bethesda'},
    '09-22': {y:2021,t:'Kena Bridge',d:'Ember Lab выпускает Kena: Bridge of Spirits — инди-шедевр с Pixar-графикой'},
    '09-23': {y:2006,t:'Wii цена',d:'Nintendo объявляет цену Wii — $249 с Wii Sports в комплекте'},
    '09-24': {y:2019,t:'The Last of Us 2',d:'Sony анонсирует дату выхода TLOU2 — 21 февраля 2020 (позже перенесена)'},
    '09-25': {y:2018,t:'Valve Artifact',d:'Valve анонсирует Artifact: The Dota Card Game — $1M турнир до релиза'},
    '09-26': {y:2017,t:'Fortnite BR',d:'Epic Games запускает Fortnite Battle Royale — бесплатная альтернатива PUBG'},
    '09-27': {y:2019,t:'Code Vein',d:'Bandai Namco выпускает Code Vein — аниме-соулслайк с вампирами'},
    '09-28': {y:2020,t:'Genshin Impact',d:'miHoYo выпускает Genshin Impact — $2 млрд за первый год, феномен gacha'},
    '09-29': {y:1998,t:'Banjo Tooie',d:'Rare анонсирует Banjo-Tooie — долгожданное продолжение на N64'},
    '09-30': {y:2014,t:'Forza Horizon 2',d:'Playground Games выпускает Forza Horizon 2 — рождение гоночного шедевра'},

    '10-01': {y:2015,t:'The Taken King',d:'Destiny: The Taken King спасает франшизу — 8.5/10 повсюду'},
    '10-02': {y:2001,t:'ICO',d:'Team Ico выпускает ICO в США — минималистичный шедевр, вдохновивший поколение'},
    '10-03': {y:2017,t:'Star Wars BF2',d:'EA/DICE показывают Star Wars Battlefront II бету — скандал с лутбоксами'},
    '10-04': {y:2016,t:'PlayStation VR',d:'Sony анонсирует PlayStation VR дату — 13 октября 2016, $399'},
    '10-05': {y:2017,t:'Google Stadia',d:'Google начинает внутреннее тестирование Project Stream — будущая Stadia'},
    '10-06': {y:2015,t:'Discord',d:'Discord выходит из беты — будущий стандарт голосового общения геймеров'},
    '10-07': {y:2016,t:'Mafia III',d:'Hangar 13 выпускает Mafia III — атмосферный Нью-Бордо 1968 года'},
    '10-08': {y:1996,t:'IGN.com',d:'Запущен IGN.com — крупнейший игровой медиа-сайт'},
    '10-09': {y:2018,t:'Google Stadia',d:'Google официально представляет Project Stream — тест AC Odyssey в браузере'},
    '10-10': {y:2017,t:'Shadow of War',d:'Monolith выпускает Middle-earth: Shadow of War — система Nemesis 2.0'},
    '10-11': {y:2018,t:'Black Ops IIII',d:'Treyarch выпускает Call of Duty: Black Ops 4 без сингл-кампании'},
    '10-12': {y:2016,t:'Oculus Touch',d:'Oculus представляет Touch-контроллеры — VR с руками, цена $199'},
    '10-13': {y:2016,t:'PlayStation VR',d:'Sony выпускает PlayStation VR — консольный VR за $399'},
    '10-14': {y:2000,t:'PS2',d:'Sony официально анонсирует PlayStation 2 в Японии'},
    '10-15': {y:2015,t:'Guitar Hero Live',d:'Activision перезапускает Guitar Hero с FMV-видео и новой гитарой'},
    '10-16': {y:2012,t:'Dishonored',d:'Arkane Studios выпускает Dishonored — стелс-шедевр в стимпанк-Дануолле'},
    '10-17': {y:2017,t:'EA закрытие',d:'EA закрывает Visceral Games — студия Dead Space закрыта посреди Star Wars'},
    '10-18': {y:2007,t:'Orange Box',d:'Valve выпускает The Orange Box — Portal, TF2, HL2: Episodes в одном боксе'},
    '10-19': {y:2019,t:'EA доступ Steam',d:'EA возвращается в Steam — Jedi Fallen Order первый новый тайтл за 8 лет'},
    '10-20': {y:2017,t:'Nintendo Switch',d:'Switch продаётся тиражом 7.63M за 7 месяцев — сравнение с PS4 и Wii'},
    '10-21': {y:2008,t:'Fable II',d:'Lionhead Studios выпускает Fable II — «РПГ для тех, кто не любит РПГ»'},
    '10-22': {y:2019,t:'Modern Warfare',d:'Infinity Ward перезапускает Call of Duty: Modern Warfare'},
    '10-23': {y:1996,t:'Tomb Raider',d:'Core Design выпускает Tomb Raider на ПК — 7M копий, Лара становится иконой'},
    '10-24': {y:2014,t:'Civilization BE',d:'Firaxis выпускает Civilization: Beyond Earth — Сид Мейер в космосе'},
    '10-25': {y:2019,t:'The Outer Worlds',d:'Obsidian выпускает The Outer Worlds — Fallout в космосе от создателей New Vegas'},
    '10-26': {y:2018,t:'Red Dead Redemption 2',d:'Rockstar выпускает Red Dead Redemption 2 — $725M за 3 дня, шедевр поколения'},
    '10-27': {y:2017,t:'Mario Odyssey',d:'Nintendo выпускает Super Mario Odyssey — возвращение к sandbox-ф ормуле'},
    '10-28': {y:2014,t:'Sunset Overdrive',d:'Insomniac выпускает Sunset Overdrive — паркур-эксклюзив Xbox One'},
    '10-29': {y:2013,t:'Battlefield 4',d:'DICE выпускает Battlefield 4 — разрушаемость Levolution, провальный запуск'},
    '10-30': {y:2015,t:'Xbox Elite',d:'Microsoft выпускает Xbox Elite Controller — премиум-геймпад за $149'},
    '10-31': {y:1999,t:'Dreamcast EU',d:'Sega выпускает Dreamcast в Европе — Sonic Adventure в комплекте'},

    '11-01': {y:2019,t:'Death Stranding',d:'Обзоры Death Stranding разделяют критиков — от 3.5/10 до 10/10'},
    '11-02': {y:2016,t:'PS4 Pro трейлер',d:'Sony выпускает трейлер PS4 Pro — апскейлинг до 4K на консолях'},
    '11-03': {y:2017,t:'Xbox One X',d:'Microsoft выпускает Xbox One X — первая консоль с 6 TFLOPS и 4K'},
    '11-04': {y:2015,t:'Black Ops III',d:'Treyarch выпускает Call of Duty: Black Ops III — зомби-режим и кибер-война'},
    '11-05': {y:2019,t:'RDR2 PC',d:'Rockstar выпускает Red Dead Redemption 2 на ПК — баги, краши, апдейты'},
    '11-06': {y:2018,t:'Diablo Immortal',d:'Blizzard анонсирует Diablo Immortal на BlizzCon — «У вас нет телефонов?»'},
    '11-07': {y:2014,t:'Advanced Warfare',d:'Sledgehammer Games выпускает CoD: Advanced Warfare — экзоскелеты и Кевин Спейси'},
    '11-08': {y:2019,t:'Death Stranding',d:'Kojima Productions выпускает Death Stranding на PS4 — симулятор курьера'},
    '11-09': {y:2010,t:'Black Ops',d:'Treyarch выпускает Call of Duty: Black Ops — $650M за 5 дней'},
    '11-10': {y:2015,t:'Fallout 4',d:'Bethesda выпускает Fallout 4 — 12M копий за 24 часа, рекорд Bethesda'},
    '11-11': {y:2011,t:'Skyrim',d:'Bethesda выпускает The Elder Scrolls V: Skyrim — 60M+ копий, игра-легенда'},
    '11-12': {y:2020,t:'PS5',d:'Sony выпускает PlayStation 5 в США, Японии и Канаде — крупнейший запуск в истории'},
    '11-13': {y:2018,t:'Hitman 2',d:'IO Interactive выпускает Hitman 2 — студия-инди, выжившая после Square Enix'},
    '11-14': {y:2017,t:'SW Battlefront II',d:'Star Wars Battlefront II — скандал с лутбоксами меняет законодательство'},
    '11-15': {y:2013,t:'PS4',d:'Sony выпускает PlayStation 4 в Северной Америке — 1M за 24 часа'},
    '11-16': {y:2017,t:'EA лутбоксы',d:'Бельгия объявляет лутбоксы азартными играми — расследование EA и Blizzard'},
    '11-17': {y:2020,t:'Godfall',d:'Counterplay Games выпускает Godfall — первый эксклюзив PS5, looter-slasher'},
    '11-18': {y:2006,t:'Wii',d:'Nintendo выпускает Wii в США — motion-контроль меняет всё, 101M продаж'},
    '11-19': {y:2021,t:'Halo Infinite',d:'Бесплатный мультиплеер Halo Infinite выходит внезапно — в честь 20-летия Xbox'},
    '11-20': {y:2020,t:'Cyberpunk 2077',d:'CD Projekt RED откладывает Cyberpunk 2077 в пятый раз — мем «when it\'s ready»'},
    '11-21': {y:1990,t:'Super Mario World',d:'Nintendo выпускает Super Mario World в Японии — стартовый тайтл SNES'},
    '11-22': {y:2013,t:'Xbox One',d:'Microsoft выпускает Xbox One — 13 стран, Kinect в комплекте, $499'},
    '11-23': {y:2004,t:'WoW',d:'Blizzard выпускает World of Warcraft — 12M подписчиков на пике, MMO-феномен'},
    '11-24': {y:2005,t:'Xbox 360',d:'Microsoft выпускает Xbox 360 — Red Ring of Death и величие HD-эры'},
    '11-25': {y:2014,t:'Dragon Age Inq.',d:'BioWare выпускает Dragon Age: Inquisition — GOTY 2014, возвращение формы'},
    '11-26': {y:2013,t:'PS Vita TV',d:'Sony анонсирует PS Vita TV в Японии — микроконсоль за ¥9 954'},
    '11-27': {y:2015,t:'Steam Link',d:'Valve выпускает Steam Link — стриминг игр с ПК на ТВ за $49'},
    '11-28': {y:2010,t:'Steam праздник',d:'Valve запускает первую Steam Holiday Sale — традиция скидок'},
    '11-29': {y:2009,t:'Steam инвентарь',d:'Valve вводит Steam Inventory и Trading — экономика скинов'},
    '11-30': {y:1998,t:'Dreamcast',d:'Sega анонсирует Dreamcast в Японии — последняя консоль компании'},

    '12-01': {y:2018,t:'The Game Awards',d:'TGA 2018 — God of War vs RDR2, новый трейлер Death Stranding'},
    '12-02': {y:2020,t:'Cyberpunk 2077',d:'CD Projekt RED показывает финальный трейлер Cyberpunk 2077 перед релизом'},
    '12-03': {y:1994,t:'PlayStation',d:'Sony выпускает первую PlayStation в Японии — 102M консолей, революция'},
    '12-04': {y:2014,t:'Game Awards',d:'The Game Awards 2014 — Zelda Wii U, MGS V, Bloodborne дата'},
    '12-05': {y:2019,t:'Resident Evil 3',d:'Capcom анонсирует ремейк Resident Evil 3 на State of Play'},
    '12-06': {y:2018,t:'Super Smash Ult.',d:'Nintendo выпускает Super Smash Bros. Ultimate — все бойцы возвращаются'},
    '12-07': {y:2018,t:'TGA 2018',d:'The Game Awards 2018 — God of War получает GOTY, новый трейлер Marvel Ultimate Alliance 3'},
    '12-08': {y:2022,t:'TGA 2022',d:'The Game Awards 2022 — Elden Ring GOTY, Death Stranding 2, Armored Core 6'},
    '12-09': {y:2008,t:'GTA IV PC',d:'Rockstar выпускает GTA IV на ПК — технические проблемы и моды'},
    '12-10': {y:2021,t:'TGA 2021',d:'The Game Awards 2021 — It Takes Two GOTY, Elden Ring трейлер, Matrix Awakens'},
    '12-11': {y:2006,t:'Wii дата',d:'Nintendo объявляет Wii дату в Европе — 8 декабря 2006'},
    '12-12': {y:2019,t:'TGA 2019',d:'The Game Awards 2019 — Sekiro GOTY, новый Xbox Series X впервые показан'},
    '12-13': {y:2017,t:'PUBG 1.0',d:'PUBG выходит из раннего доступа — версия 1.0 с новой пустынной картой Miramar'},
    '12-14': {y:2015,t:'Steam Discovery',d:'Valve запускает Steam Discovery Update 2.0 — алгоритм рекомендаций'},
    '12-15': {y:2006,t:'Wii Sports',d:'Nintendo Europe выпускает Wii с Wii Sports — фитнес-революция в играх'},
    '12-16': {y:2020,t:'Cyberpunk 2077',d:'Sony удаляет Cyberpunk 2077 из PlayStation Store и предлагает возвраты'},
    '12-17': {y:2018,t:'Epic Games Store',d:'Epic Games запускает магазин с 88/12% разделением дохода — война со Steam'},
    '12-18': {y:1996,t:'Quake shareware',d:'id Software выпускает shareware версию Quake — интернет взрывается'},
    '12-19': {y:2019,t:'Game Awards',d:'Итоги The Game Awards 2019: Sekiro GOTY, Xbox Series X показана миру'},
    '12-20': {y:2010,t:'Valve новости',d:'Valve анонсирует систему Steam Guard для защиты аккаунтов'},
    '12-21': {y:1996,t:'Super Mario 64',d:'Nintendo выпускает Super Mario 64 в Японии — первый 3D-платформер Марио'},
    '12-22': {y:2021,t:'Steam Awards',d:'Steam Awards 2021 — Resident Evil Village GOTY по версии игроков'},
    '12-23': {y:2009,t:'MW2 бан',d:'Infinity Ward вызывает скандал банами моддеров в Modern Warfare 2 на ПК'},
    '12-24': {y:2012,t:'Steam Sale',d:'Valve запускает первую полноценную Steam Winter Sale с флеш-скидками'},
    '12-25': {y:2007,t:'Orange Box',d:'Рождественские продажи The Orange Box — миллионы игроков впервые пробуют Portal'},
    '12-26': {y:2004,t:'HL2',d:'Half-Life 2 становится игрой года по 50+ изданиям на Рождество'},
    '12-27': {y:2009,t:'Steam рекорд',d:'Steam регистрирует рекордный онлай в праздничные дни — 2009'},
    '12-28': {y:2018,t:'Итоги года',d:'Игровая индустрия подводит итоги 2018 — Fortnite и Red Dead доминируют'},
    '12-29': {y:1999,t:'Y2K',d:'Игровые студии готовятся к Y2K-багу — Battle.net, Steam и консоли под угрозой'},
    '12-30': {y:2021,t:'Итоги Steam',d:'Steam подводит итоги года — рекорды онлайна и продаж'},
    '12-31': {y:2000,t:'Итоги тысячелетия',d:'Игровые издания подводят итоги тысячелетия — лучшие игры XX века: Tetris, Mario, Zelda, Doom'}
  };

  var event = events[key];
  if (!event) { event = findClosest(key); }

  var el = document.getElementById(CONTAINER);
  el.innerHTML =
    '<div class="gh-card">' +
    '  <div class="gh-date">' + today.getDate() + ' ' + monthName(today.getMonth()) + '</div>' +
    '  <div class="gh-year">' + event.y + '</div>' +
    '  <div class="gh-title">' + esc(event.t) + '</div>' +
    '  <div class="gh-desc">' + esc(event.d) + '</div>' +
    '  <div class="gh-label">Сегодня в истории игр</div>' +
    '</div>';

  function monthName(m) {
    return ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'][m];
  }

  function findClosest(k) {
    var keys = Object.keys(events);
    var idx = keys.indexOf(k);
    if (idx >= 0) return events[k];
    for (var i = 0; i < keys.length; i++) {
      if (keys[i] > k) return events[keys[Math.max(0, i - 1)]];
    }
    return events[keys[keys.length - 1]];
  }

  function esc(str) {
    var d = document.createElement('div');
    d.textContent = str;
    return d.innerHTML;
  }
})();