name: Generate Game News Free

on:
  schedule:
    - cron: '52 8 * * *'  # каждый день в 10:00 по Москве

    
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Get 3 hot gaming news
      run: |
        curl https://raw.githubusercontent.com/1hax/news-ai-free/main/fetch_news.py -o fetch_news.py
        python3 fetch_news.py > news.json

    - name: Commit news.json
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add news.json
        git commit -m "Автоматически обновлённые игровые новости"
        git push

