name: AI News Generator

on:
  schedule:
    - cron: "0 8 * * *"  # каждый день в 08:00 UTC
  workflow_dispatch:

jobs:
  generate-news:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Ставим библиотеку OpenAI
        run: pip install openai

      - name: 🤖 Генерируем 3 горячих новости
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          import openai, json, datetime

          openai.api_key = "${{ secrets.OPENAI_API_KEY }}"
          today = datetime.date.today().isoformat()

          prompt = (
              "Сделай три самых горячих игровых новости на русском языке (по 1-2 предложения на каждую). "
              "Не пиши заголовки — просто короткие новости. Пронумеруй их: 1, 2, 3."
          )

          response = openai.ChatCompletion.create(
              model="gpt-3.5-turbo",
              messages=[
                  {"role": "system", "content": "Ты новостной ИИ-блок для геймерского сайта."},
                  {"role": "user", "content": prompt}
              ]
          )

          raw = response.choices[0].message['content'].strip()
          lines = [line.strip()[2:].strip() for line in raw.split("\n") if line.strip().startswith(("1", "2", "3"))]

          news_items = [{"date": today, "text": line} for line in lines]

          try:
              with open("news.json", "r", encoding="utf-8") as f:
                  existing = json.load(f)
          except:
              existing = []

          all_news = news_items + existing
          all_news = all_news[:15]  # максимум 15 штук

          with open("news.json", "w", encoding="utf-8") as f:
              json.dump(all_news, f, ensure_ascii=False, indent=2)

      - name: 💾 Коммитим новости
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add news.json
          git commit -m "🔥 Автообновление горячих новостей"
          git push
