name: Генерация новостей при обновлении

on:
  push:        # При любом пуше
    branches: [ main ]
  workflow_dispatch: # И вручную можно запускать

jobs:
  generate-news:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем зависимости
        run: pip install requests

      - name: Запускаем генератор новостей
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python fetch_news.py

      - name: Коммитим новости обратно
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add news.json
          git commit -m "Автоматически сгенерированные новости"
          git push

